# Generated by Django 2.1.5 on 2020-11-27 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_contactus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ('create',)},
        ),
        migrations.AddField(
            model_name='contactus',
            name='create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
